apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/chart: awx-operator-0.18.8
  name: awx-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get

