name: helm-release

on:
  push:
    branches: [helm2]
  # push:
  #   tags:
  #     - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: ./charts
        # with:
        #   fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Create Helm chart
        run: |
          echo VERSION: $VERSION
          make helm-chart
        env:
          VERSION: ${{ github.ref_name }}

      - name: Chart releaser
        run: |
          # Download chart releaser
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v${CR_VERSION}/chart-releaser_${CR_VERSION}_linux_amd64.tar.gz
          echo "$CR_CHECKSUM  chart-releaser_${CR_VERSION}_linux_amd64.tar.gz" | sha256sum --check
          tar -xzf chart-releaser_${CR_VERSION}_linux_amd64.tar.gz
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          exists=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$owner/$repo/releases/tags/$repo-${{ steps.fix_tag.outputs.tag }} -w %{http_code} -o /dev/null)
          if [[ $exists != "200" ]]; then
            echo "Creating release..."
            # package chart
            ./cr package $CHART_PATH
            # upload chart to github releases
            #./cr upload \
            #    --owner "$owner" \
            #    --git-repo "$repo" \
            #    --token "${{ secrets.GITHUB_TOKEN }}"
            # Update index and push to github pages
            #./cr index \
            #    --owner "$owner" \
            #    --git-repo "$repo" \
            #    --token "${{ secrets.GITHUB_TOKEN }}" \
            #    --charts-repo ${{ inputs.chart_url }} \
            #    --push
          else
            echo "Release already exists"
          fi
        env:
          CR_VERSION: 1.3.0
          CR_CHECKSUM: baed2315a9bb799efb71d512c5198a2a3b8dcd139d7f22f878777cffcd649a37
          CHART_PATH: ./charts

      # - name: Commit Helm chart
      #   uses: EndBug/add-and-commit@v8
      #   with:
      #     author_name: "$GITHUB_ACTOR"
      #     author_email: "$GITHUB_ACTOR@users.noreply.github.com"
      #     message: "Adding Helm chart ${VERSION}"
      #     cwd: ./charts/
      #     push: false
      #     # tag: "${{ github.ref_name }} --force"
      #   env:
      #     VERSION: ${{ github.ref_name }}

      # - uses: actions-ecosystem/action-get-latest-tag@v1
      #   id: get-latest-tag

      # - uses: actions-ecosystem/action-bump-semver@v1
      #   id: bump-semver
      #   with:
      #     current_version: ${{ steps.get-latest-tag.outputs.tag }}
      #     level: patch

      # - uses: actions-ecosystem/action-push-tag@v1
      #   with:
      #     tag: ${{ steps.bump-semver.outputs.new_version }}
      #     message: "Bumping to ${{ steps.bump-semver.outputs.new_version }} for helm/chart-releaser"
      #     # message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.3.0
      #   with:
      #     charts_dir: charts
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
