name: helm-release

on:
  # push:
  #   branches: [helm2]
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: ./charts
        # with:
        #   fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Create Helm chart
        run: |
          echo VERSION: $VERSION
          make helm-chart
        env:
          VERSION: ${{ github.ref_name }}

      - name: Commit Helm chart
        uses: EndBug/add-and-commit@v8
        with:
          author_name: "$GITHUB_ACTOR"
          author_email: "$GITHUB_ACTOR@users.noreply.github.com"
          message: "Adding Helm chart ${VERSION}"
          cwd: ./charts/
          push: false
          tag: "${{ github.ref_name }} --force"
        env:
          VERSION: ${{ github.ref_name }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: "Bumping to ${{ steps.bump-semver.outputs.new_version }} for helm/chart-releaser"
          # message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
