name: helm-release

on:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Create Helm chart
        run: |
          echo VERSION: $VERSION
          make helm-chart
        env:
          VERSION: ${{ github.ref_name }}

      - name: Release Helm chart
        run: |
          echo VERSION: $VERSION
          make helm-release
        env:
          VERSION: ${{ github.ref_name }}

      # # Reinventing the wheel if/until https://github.com/helm/chart-releaser-action/pull/96 is merged
      # - name: Release Helm chart
      #   run: |
      #     echo "== Downloading chart releaser =="
      #     wget -cq https://github.com/helm/chart-releaser/releases/download/v${CR_VERSION}/chart-releaser_${CR_VERSION}_linux_amd64.tar.gz
      #     echo "$CR_CHECKSUM  chart-releaser_${CR_VERSION}_linux_amd64.tar.gz" | sha256sum --check
      #     tar -xzf chart-releaser_${CR_VERSION}_linux_amd64.tar.gz

      #     repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
      #     owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")

      #     echo "== Packaging chart into a release =="
      #     ./cr package \
      #       ${CHART_PATH}/${repo}

      #     echo "Uploading release to repository =="
      #     ./cr upload \
      #        --owner "$owner" \
      #        --git-repo "$repo" \
      #        --token "${{ secrets.GITHUB_TOKEN }}" \
      #        --skip-existing

      #     git fetch --all

      #     echo "== Updating Helm repository index =="
      #     ./cr index \
      #        --owner "$owner" \
      #        --git-repo "$repo" \
      #        --token "${{ secrets.GITHUB_TOKEN }}" \
      #        --pages-branch $PAGES_BRANCH \
      #        --index-path $INDEX_PATH \
      #        --charts-repo https://${owner}.github.io/${repo}/${INDEX_PATH} \
      #        --push
      #   env:
      #     CR_VERSION: 1.3.0
      #     CR_CHECKSUM: baed2315a9bb799efb71d512c5198a2a3b8dcd139d7f22f878777cffcd649a37
      #     CHART_PATH: ./charts
      #     PAGES_BRANCH: gh-pages
      #     INDEX_PATH: index.yaml
      #     VERSION: ${{ github.ref_name }}

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.3.0
      #   with:
      #     charts_dir: charts
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
