name: helm-release

on:
  # push:
  #   branches: [helm2]
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: ./charts
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Create Helm chart
        run: |
          echo VERSION: $VERSION
          make helm-chart
        env:
          VERSION: ${{ github.ref_name }}

      - name: Commit Helm chart
        uses: EndBug/add-and-commit@v8
        with:
          message: Adding Helm chart $VERSION
          cwd: ./charts/
          push: false
        env:
          VERSION: ${{ github.ref_name }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
